/*
 * This source file was generated by the Gradle 'init' task
 */
package org.graphincalculator;

import org.graphingcalculator.Calculator;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Calculator classUnderTest = new Calculator();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
